/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryjava;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rashi
 */
public class ItemsInStock extends javax.swing.JFrame {

    /**
     * Creates new form ItemsInStock
     */
    public ItemsInStock() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2,size.height/2-getHeight()/2);
        table_update();
    }

   Connection con;
   PreparedStatement pst,pst1,pst2,pst3,pst4,pst5;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ProductMain = new javax.swing.JLabel();
        SalesMain = new javax.swing.JLabel();
        DamagedMain = new javax.swing.JLabel();
        DamagedMain1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Types", "Code", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable6.getTableHeader().setReorderingAllowed(false);
        jTable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable6MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable6);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 51, 0));
        jLabel17.setText("Available Products");

        jPanel3.setBackground(new java.awt.Color(153, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(jLabel17)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel17)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 51, 0));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Inventory Management System");

        ProductMain.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ProductMain.setForeground(new java.awt.Color(255, 255, 255));
        ProductMain.setText("Product");
        ProductMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductMainMouseClicked(evt);
            }
        });

        SalesMain.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        SalesMain.setForeground(new java.awt.Color(255, 255, 255));
        SalesMain.setText("Sales");
        SalesMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalesMainMouseClicked(evt);
            }
        });

        DamagedMain.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        DamagedMain.setForeground(new java.awt.Color(255, 255, 255));
        DamagedMain.setText("Damaged");
        DamagedMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DamagedMainMouseClicked(evt);
            }
        });

        DamagedMain1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        DamagedMain1.setForeground(new java.awt.Color(255, 255, 255));
        DamagedMain1.setText("Items in Stock");
        DamagedMain1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DamagedMain1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(ProductMain)
                .addGap(251, 251, 251)
                .addComponent(SalesMain)
                .addGap(320, 320, 320)
                .addComponent(DamagedMain, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DamagedMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(465, 465, 465)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductMain)
                    .addComponent(SalesMain)
                    .addComponent(DamagedMain)
                    .addComponent(DamagedMain1))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_update()
    {
    
        try {
            
            int c,count;
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/hamrocolorsansar","root","");
                pst = con.prepareStatement("select * from products");
                pst1 =  con.prepareStatement("select * from sales");
                pst2 =  con.prepareStatement("select * from damaged");
                 pst3 = con.prepareStatement("select * from sales where id=?");
                ResultSet rs = pst.executeQuery();
                 pst5=con.prepareStatement("truncate table stock");
                   pst5.executeUpdate();
                
               pst3.setInt(1, 1);
                 ResultSet rs3 = pst3.executeQuery();
                 rs3.next();
 //               System.out.println(rs3.getInt("qty"));
                ResultSetMetaData rsd = rs.getMetaData();
                c = rsd.getColumnCount();
                
                DefaultTableModel d = (DefaultTableModel)jTable6.getModel();
                d.setRowCount(0);
                
                while(rs.next()) 
                {
 //                    System.out.println(rs.getString("id"));
                    count=rs.getInt("qty");
                     ResultSet rs1 = pst1.executeQuery();
                     ResultSet rs2 = pst2.executeQuery();
                    while(rs1.next()){
 //                        System.out.println(rs1.getString("Code"));
                        if((rs.getString("Code")).equals(rs1.getString("Code"))){
                           count-=rs1.getInt("qty");
 //                      System.out.println(count);
                        }
                        
                    }
                    while(rs2.next()){
//                        System.out.println("yoo");
                        if(rs.getString("Code")==rs2.getString("Code")){
                           
                           count-=rs2.getInt("Dmgpec");
                           
                        }
                        
                    }
//                    System.out.println(count);
//                    if(count==0){
//                        Vector v2 = new Vector(); 
//                   for(int i=1; i<=c; i++){
//                       v2.add(rs.getString("id"));
//                       v2.add(rs.getString("Name"));
//                       v2.add(rs.getString("Types"));
//                       v2.add(rs.getString("Code"));
//                       v2.add(rs.getString("Qty"));
//                   }
//                
//                   d.addRow(v2);
//                    }
//                    else{
//                        int Qty=count;
//                         Vector v2 = new Vector(); 
//                   for(int i=1; i<=c; i++){
//                       v2.add(rs.getString("id"));
//                       v2.add(rs.getString("Name"));
//                       v2.add(rs.getString("Types"));
//                       v2.add(rs.getString("Code"));
//                      
//                       v2.add(Qty);
//                   }
//                
//                   d.addRow(v2);
//                    }
//                 
                    int Qty=count;
                         Vector v2 = new Vector(); 
                   for(int i=1; i<=c; i++){
                     //  v2.add(rs.getString("id"));
                      
                       v2.add(rs.getString("Name"));
                       v2.add(rs.getString("Types"));
                       v2.add(rs.getString("Code"));
                       v2.add(Qty);
                       
                   }
                    d.addRow(v2);
  //                 System.out.println(rs.getString("id"));
                   
                    pst4 =con.prepareStatement("insert into stock(Name,Types,Code,Qty)values(?,?,?,?)");
//                    pst4.setString(1, rs.getString("id"));
                    pst4.setString(1, rs.getString("Name"));
                    pst4.setString(2, rs.getString("Types"));
                    pst4.setString(3,rs.getString("Code"));
                    pst4.setInt(4,Qty);
                    pst4.executeUpdate();
                    
                }
         
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
     
    private void jTable6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable6MouseClicked
        // TODO add your handling code here:
        DefaultTableModel d1 = (DefaultTableModel)jTable6.getModel();
        int selectIndex = jTable6.getSelectedRow();

//        
    }//GEN-LAST:event_jTable6MouseClicked

    private void ProductMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductMainMouseClicked
        // TODO add your handling code here:
        new MainForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductMainMouseClicked

    private void DamagedMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DamagedMainMouseClicked
        // TODO add your handling code here:
        new Damaged().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DamagedMainMouseClicked

    private void DamagedMain1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DamagedMain1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DamagedMain1MouseClicked

    private void SalesMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalesMainMouseClicked
        // TODO add your handling code here:
        new Sales().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SalesMainMouseClicked

    
    //private void UpdateQty() throws ClassNotFoundException, SQLException{
       // if(Integer.valueOf(Qty.getText())>);
//        try{
//          
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            con = DriverManager.getConnection("jdbc:mysql://localhost/hamrocolorsansar","root","");
//            pst =con.prepareStatement("update Stock set Qty=? where id=?");
//            pst.setInt(1, );
//        }
//        
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemsInStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemsInStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemsInStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemsInStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemsInStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DamagedMain;
    private javax.swing.JLabel DamagedMain1;
    private javax.swing.JLabel ProductMain;
    private javax.swing.JLabel SalesMain;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable6;
    // End of variables declaration//GEN-END:variables
}
